version: '3.8'

services:
  mysql:
    build:
      context: ./docker-ads/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ads_db
      MYSQL_USER: dotskin
      MYSQL_PASSWORD: 123
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: always

  nginx:
    build:
      context: ./docker-ads/nginx
    container_name: nginx
    depends_on:
      - django-app
    volumes:
      - ./docker-ads/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker-ads/nginx/sites-available:/etc/nginx/sites-available
      - ./docker-ads/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client:/var/www/advertisements-service/client
    ports:
      - "80:80"
    networks:
      - backend
    restart: always

  django-app:
    build:
      context: ./api
    container_name: django-app
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=ads_db
      - DB_USER=dotskin
      - DB_PASSWORD=123
    volumes:
      - ./api:/var/www/api
    ports:
      - "8000:8000"
    networks:
      - backend
    command: >
      sh -c "sleep 10 &&
      php-fpm -D"
    restart: always

  dns:
    build:
      context: ./docker-ads/dns
    container_name: dns
    networks:
      - backend
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
