version: '3.9'

services:
  nginx:
    build:
      context: ./nginx  # Путь к папке с Dockerfile для Nginx
    container_name: nginx-service
    ports:
      - "80:80"  # Пробрасывает порт 80 с хоста на контейнер
    volumes:
      - ./nginx/site/advertisements-service/client:/var/www/advertisements-service/client
    networks:
      - my_network
    depends_on:
      - dns  # Убедитесь, что DNS-сервис запускается первым

  dns:
    build:
      context: ./dns  # Путь к папке с Dockerfile для BIND9
    container_name: dns-service
    ports:
      - "1053:53/udp"  # Пробрасывает порт 53/udp с хоста на контейнер
      - "1053:53/tcp"  # Пробрасывает порт 53/tcp с хоста на контейнер
    volumes:
      - ./dns/bind9:/etc/bind  # Копирует конфигурационные файлы BIND9 в контейнер
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
