version: "3.8"

services:
  nginx:
    image: dotskinmaksim/ads-nginx-image:latest  # Укажите имя вашего образа для Nginx
    container_name: nginx2        # Имя контейнера
    ports:
      - "80:8080"                 # Прокси на порт 80 хоста
    restart: unless-stopped       # Перезапускать контейнер в случае сбоя

  mysql:
    image: dotskinmaksim/ads-sql-image:latest         # Укажите имя вашего образа для MySQL
    container_name: mysql-container  # Имя контейнера
    ports:
      - "3306:3306"               # Прокси на порт 3306 хоста
    environment:
      MYSQL_ROOT_PASSWORD: 123    # Укажите пароль для root
      MYSQL_DATABASE: ads_database  # Имя базы данных
    restart: unless-stopped       # Перезапускать контейнер в случае сбоя



