version: "3.8"

services:
  nginx:
    image: nginx-service10:latest  # Укажите имя вашего образа для Nginx
    container_name: nginx-container        # Имя контейнера
    ports:
      - "80:8080"                 # Прокси на порт 80 хоста
    restart: unless-stopped
    dns:
      - 172.18.0.3  # Здесь указываете IP вашего DNS-контейнера

  mysql:
    image: mysql-db2:latest         # Укажите имя вашего образа для MySQL
    container_name: mysql-container  # Имя контейнера
    ports:
      - "3306:3306"               # Прокси на порт 3306 хоста
    environment:
      MYSQL_ROOT_PASSWORD: 123    # Укажите пароль для root
      MYSQL_DATABASE: ads_database  # Имя базы данных
    restart: unless-stopped       # Перезапускать контейнер в случае сбоя

  dns:
    image: dns-service:latest         # Укажите имя вашего образа для DNS-сервера (например, bind9)
    container_name: dns-container  # Имя контейнера
    ports:
      - "5353:53/udp"                # Прокси на порт 53 UDP хоста
      - "5353:53/tcp"                # Прокси на порт 53 TCP хоста
    restart: unless-stopped       # Перезапускать контейнер в случае сбоя
